import type { Subsystem } from "@/lib/fault-disruptors/data"
import { DOWNLOAD_NAME } from "@/lib/fault-disruptors/api"
import type { AnalysisJob, DashboardWorkspace } from "@/lib/fault-disruptors/workspace"
import { strToU8, zipSync } from "fflate"

/**
 * Natural sort helper so Test1, Test2, ... Test10 sort in human numerical order.
 */
function naturalSort<T>(items: T[], keyFn: (item: T) => string): T[] {
  return [...items].sort((a, b) =>
    keyFn(a).localeCompare(keyFn(b), undefined, { numeric: true, sensitivity: "base" }),
  )
}

/**
 * Merge individual job outputs into the official subsystem submission CSV format.
 */
export function buildSubsystemMergedCsv(subsystem: Subsystem, jobs: AnalysisJob[]): string {
  const completed = jobs.filter((job) => job.status === "complete" && job.result)
  if (completed.length === 0) return ""

  const sortedJobs = naturalSort(completed, (j) => j.fileName)

  if (subsystem === "RAIL") {
    const lines = ["file_id,prediction"]
    for (const job of sortedJobs) {
      const pred = String(job.result?.prediction ?? "Normal")
      lines.push(`${job.fileName},${pred}`)
    }
    return lines.join("\n") + "\n"
  }

  if (subsystem === "SHM") {
    const lines = ["file_id,prediction"]
    for (const job of sortedJobs) {
      const pred =
        typeof job.result?.prediction === "number"
          ? job.result.prediction.toFixed(4)
          : String(job.result?.prediction ?? "")
      lines.push(`${job.fileName},${pred}`)
    }
    return lines.join("\n") + "\n"
  }

  if (subsystem === "DOOR") {
    // For Door, each row is a cycle. Combine across all files without repeating headers.
    const lines = ["start_time,end_time,prediction"]
    for (const job of sortedJobs) {
      const table = Array.isArray(job.result?.table) ? job.result!.table : []
      for (const row of table) {
        lines.push(`${row.start_time},${row.end_time},${row.prediction}`)
      }
    }
    // Fallback if table is empty but submission_csv exists
    if (lines.length === 1 && sortedJobs[0]?.result?.submission_csv) {
      return sortedJobs[0].result.submission_csv
    }
    return lines.join("\n") + "\n"
  }

  if (subsystem === "ACV") {
    // ACV ranks carriages for each test file: file_id,ranked_cars
    const lines = ["file_id,ranked_cars"]
    for (const job of sortedJobs) {
      const rankedCars = job.result?.table
        ? JSON.stringify(job.result.table.map((r: any) => Number(r.car)))
        : "[]"
      lines.push(`${job.fileName},"${rankedCars}"`)
    }
    if (lines.length === 1 && sortedJobs[0]?.result?.submission_csv) {
      return sortedJobs[0].result.submission_csv
    }
    return lines.join("\n") + "\n"
  }

  return ""
}

/** Download the merged submission CSV for a single subsystem in browser memory. */
export function downloadMergedSubsystemCsv(subsystem: Subsystem, jobs: AnalysisJob[]) {
  const csv = buildSubsystemMergedCsv(subsystem, jobs)
  if (!csv) return

  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }))
  const link = document.createElement("a")
  link.href = url
  link.download = DOWNLOAD_NAME[subsystem]
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

/**
 * Generate a comprehensive Markdown maintenance summary combining all active subsystems.
 */
export function generateFleetReportMarkdown(dashboard: DashboardWorkspace): string {
  const train = dashboard.selectedTrain
  const now = new Date().toUTCString()
  const activeSubsystems = (Object.keys(dashboard.workspaces) as Subsystem[]).filter(
    (sub) => dashboard.workspaces[sub].jobs.some((j) => j.status === "complete" && j.result),
  )

  let md = `# FAULT DISRUPTORS — Master Fleet Maintenance Report\n\n`
  md += `**Consist / Fleet Unit:** ${train}  \n`
  md += `**Generated:** ${now}  \n`
  md += `**Subsystems Included:** ${activeSubsystems.join(", ")}  \n\n`
  md += `> **Operational Disclaimer:** This report is generated by the Fault Disruptors decision-support dashboard to assist depot maintenance prioritization. Predictions and suggested checks must be confirmed through professional physical inspection and calibrated depot tools prior to component replacement or track milling.\n\n`
  md += `---\n\n`

  md += `## 1. Executive Fleet Summary\n\n`
  md += `| Subsystem | Completed Records | Primary Assessment | Top Action Item |\n`
  md += `| :--- | :--- | :--- | :--- |\n`

  for (const sub of activeSubsystems) {
    const ws = dashboard.workspaces[sub]
    const completed = ws.jobs.filter((j) => j.status === "complete" && j.result)
    let assessment = "Normal"
    let action = "Continue routine monitoring"

    if (sub === "ACV") {
      const topCar = completed[0]?.result?.table?.[0]?.car ?? "Unknown"
      assessment = `Car ${topCar} Elevated Leak Risk`
      action = `Inspect Car ${topCar} refrigerant circuit & compressor pressure`
    } else if (sub === "DOOR") {
      let totalCycles = 0
      let abnormalCycles = 0
      for (const j of completed) {
        const table = j.result?.table ?? []
        totalCycles += table.length
        abnormalCycles += table.filter((r: any) => r.prediction === "Abnormal resistance").length
      }
      if (abnormalCycles > 0) {
        assessment = `${abnormalCycles} of ${totalCycles} Cycles Over Limit`
        action = `Schedule door mechanism inspection at next depot stop`
      } else {
        assessment = `All ${totalCycles} Cycles Normal`
        action = `No immediate mechanical intervention required`
      }
    } else if (sub === "RAIL") {
      const faults = completed.filter((j) => j.result?.prediction !== "Normal")
      if (faults.length > 0) {
        const sides = Array.from(new Set(faults.map((j) => String(j.result?.prediction)))).join(", ")
        assessment = `${faults.length} Corrugation Windows (${sides})`
        action = `Prioritize track grinding for identified corrugation segments`
      } else {
        assessment = `All ${completed.length} Windows Normal`
        action = `Track surface within acceptable bounds`
      }
    } else if (sub === "SHM") {
      const maxD = Math.max(...completed.map((j) => Number(j.result?.prediction) || 0))
      assessment = `Max Fatigue Damage D = ${maxD.toFixed(4)}`
      if (maxD >= 0.8) {
        action = `High cumulative damage: schedule detailed non-destructive testing (NDT)`
      } else if (maxD >= 0.5) {
        action = `Moderate fatigue damage: monitor closely during periodic overhauls`
      } else {
        action = `Damage within nominal baseline`
      }
    }

    md += `| **${sub}** | ${completed.length} file(s) | ${assessment} | ${action} |\n`
  }

  md += `\n---\n\n`

  // Detailed Subsystem Breakdowns
  if (activeSubsystems.includes("ACV")) {
    const completed = dashboard.workspaces.ACV.jobs.filter((j) => j.status === "complete" && j.result)
    md += `## 2. Air Conditioning & Ventilation (ACV) — Refrigerant Leak Detection\n\n`
    for (const job of completed) {
      const table = Array.isArray(job.result?.table) ? job.result!.table : []
      const margin = job.result?.summary?.margin
      md += `### Recording: \`${job.fileName}\`\n`
      if (typeof margin === "number") {
        md += `* **Top-Ranked Separation Margin:** ${(margin * 100).toFixed(1)}% above next car\n\n`
      }
      md += `| Rank | Carriage | Anomaly Score | Risk Level | Inspection Priority |\n`
      md += `| :---: | :---: | :---: | :---: | :--- |\n`
      for (const row of table) {
        const score = typeof row.score === "number" ? row.score.toFixed(4) : "—"
        md += `| ${row.rank} | Car ${row.car} | ${score} | ${row.risk ?? "neutral"} | ${row.rank === 1 ? "**Priority Inspection**" : "Routine"} |\n`
      }
      md += `\n`
    }
    md += `---\n\n`
  }

  if (activeSubsystems.includes("DOOR")) {
    const completed = dashboard.workspaces.DOOR.jobs.filter((j) => j.status === "complete" && j.result)
    md += `## 3. Passenger Door Mechanisms — Operating Resistance Diagnostics\n\n`
    for (const job of completed) {
      const table = Array.isArray(job.result?.table) ? job.result!.table : []
      const abnormal = table.filter((r: any) => r.prediction === "Abnormal resistance")
      const review = table.filter(
        (r: any) =>
          String(r.confidence ?? "").toLowerCase().startsWith("low") ||
          (r.quality_flags && String(r.quality_flags).length > 0),
      )

      md += `### Telemetry Stream: \`${job.fileName}\`\n`
      md += `* **Total Cycles Detected:** ${table.length}\n`
      md += `* **Abnormal Resistance Cycles:** ${abnormal.length} (${table.length > 0 ? Math.round((abnormal.length / table.length) * 100) : 0}%)\n`
      md += `* **Low-Confidence / Review Cycles:** ${review.length}\n\n`

      if (abnormal.length > 0) {
        md += `#### Flagged Abnormal Resistance Cycles:\n`
        md += `| Time | Operation | Resistance (% of Limit) | Quality Flags | Maintenance Action |\n`
        md += `| :---: | :---: | :---: | :---: | :--- |\n`
        for (const row of abnormal.slice(0, 15)) {
          const pct = row.threshold ? Math.round((row.resistance_ratio / row.threshold) * 100) : "—"
          md += `| ${row.start_time} | ${row.operation ?? "—"} | ${pct}% | ${row.quality_flags || "None"} | Inspect roller guides, seal friction & motor track |\n`
        }
        if (abnormal.length > 15) {
          md += `*...and ${abnormal.length - 15} more abnormal cycles.*\n`
        }
      } else {
        md += `*All operating cycles within normal resistance bounds (ratio below limit threshold).*\n`
      }
      md += `\n`
    }
    md += `---\n\n`
  }

  if (activeSubsystems.includes("RAIL")) {
    const completed = dashboard.workspaces.RAIL.jobs.filter((j) => j.status === "complete" && j.result)
    const sorted = naturalSort(completed, (j) => j.fileName)
    const normalCount = sorted.filter((j) => j.result?.prediction === "Normal").length
    const side1Count = sorted.filter((j) => j.result?.prediction === "Side I").length
    const side2Count = sorted.filter((j) => j.result?.prediction === "Side II").length

    md += `## 4. Rail Corrugation Monitoring — Track Assessment\n\n`
    md += `* **Total Recording Windows:** ${sorted.length}\n`
    md += `* **Normal Segments:** ${normalCount}\n`
    md += `* **Side I Corrugation:** ${side1Count}\n`
    md += `* **Side II Corrugation:** ${side2Count}\n\n`

    md += `### Complete Segment Inventory:\n`
    md += `| Recording File | Verdict | Speed (km/h) | Distance (m) | Hotspot Window (m) | Peak Local Energy |\n`
    md += `| :--- | :--- | :---: | :---: | :---: | :---: |\n`

    for (const job of sorted) {
      const pred = String(job.result?.prediction ?? "Normal")
      const speed = typeof job.result?.summary?.speed_kmh === "number" ? job.result.summary.speed_kmh.toFixed(1) : "—"
      const dist = typeof job.result?.summary?.speed_transitions === "number" ? (job.result.summary.speed_transitions * 0.014835).toFixed(2) : "—"
      const hotspot = job.result?.summary?.hotspot
      const hotspotStr = hotspot && typeof hotspot.start_m === "number" ? `${hotspot.start_m.toFixed(1)}–${hotspot.end_m.toFixed(1)} m` : "—"
      const energyStr = hotspot && typeof hotspot.peak_to_median_energy === "number" ? `${hotspot.peak_to_median_energy.toFixed(2)}× median` : "—"

      md += `| \`${job.fileName}\` | **${pred}** | ${speed} | ${dist} | ${hotspotStr} | ${energyStr} |\n`
    }
    md += `\n---\n\n`
  }

  if (activeSubsystems.includes("SHM")) {
    const completed = dashboard.workspaces.SHM.jobs.filter((j) => j.status === "complete" && j.result)
    const sorted = naturalSort(completed, (j) => j.fileName)
    const damages = sorted.map((j) => Number(j.result?.prediction) || 0)
    const maxD = damages.length > 0 ? Math.max(...damages) : 0
    const avgD = damages.length > 0 ? damages.reduce((a, b) => a + b, 0) / damages.length : 0

    md += `## 5. Structural Health Monitoring (SHM) — Cumulative Fatigue Damage\n\n`
    md += `* **Total Dynamic Stress Records:** ${sorted.length}\n`
    md += `* **Maximum Cumulative Damage (D):** ${maxD.toFixed(4)}\n`
    md += `* **Average Cumulative Damage (D):** ${avgD.toFixed(4)}\n`
    md += `* **Design Fatigue Failure Limit:** $D = 1.0$ (Miner's Rule)\n\n`

    md += `### Evaluated Stress Records:\n`
    md += `| Record File | Cumulative Damage (D) | Status / Severity | Recommended Engineering Follow-Up |\n`
    md += `| :--- | :---: | :---: | :--- |\n`

    for (const job of sorted) {
      const d = Number(job.result?.prediction) || 0
      const severity = d >= 0.8 ? "**High (>= 0.8)**" : d >= 0.5 ? "Moderate (>= 0.5)" : "Nominal (< 0.5)"
      const recommendation =
        d >= 0.8
          ? "Priority NDT inspection of critical bogie/body weld joints"
          : d >= 0.5
            ? "Inspect structural joints during next scheduled overhaul"
            : "Continue regular operational monitoring"

      md += `| \`${job.fileName}\` | **${d.toFixed(4)}** | ${severity} | ${recommendation} |\n`
    }
    md += `\n`
  }

  return md
}

/**
 * Package all active subsystem submission CSVs and the master executive report into a single ZIP.
 */
export function downloadConsolidatedFleetReport(dashboard: DashboardWorkspace) {
  const files: Record<string, Uint8Array> = {}
  const activeSubsystems = (Object.keys(dashboard.workspaces) as Subsystem[]).filter(
    (sub) => dashboard.workspaces[sub].jobs.some((j) => j.status === "complete" && j.result),
  )

  if (activeSubsystems.length === 0) return

  // 1. Generate master Markdown maintenance report
  const reportMd = generateFleetReportMarkdown(dashboard)
  files["FLEET_MAINTENANCE_REPORT.md"] = strToU8(reportMd)

  // 2. Generate and package each subsystem's merged official submission CSV
  for (const sub of activeSubsystems) {
    const csv = buildSubsystemMergedCsv(sub, dashboard.workspaces[sub].jobs)
    if (csv) {
      files[`predictions/${DOWNLOAD_NAME[sub]}`] = strToU8(csv)
    }
  }

  // 3. Add manifest
  const manifest = {
    fleet_unit: dashboard.selectedTrain,
    generated_at: new Date().toISOString(),
    active_subsystems: activeSubsystems,
    files_included: Object.fromEntries(
      activeSubsystems.map((sub) => [
        sub,
        dashboard.workspaces[sub].jobs.filter((j) => j.status === "complete").map((j) => j.fileName),
      ]),
    ),
  }
  files["manifest.json"] = strToU8(JSON.stringify(manifest, null, 2))

  // 4. Compress and trigger browser download
  const archive = zipSync(files, { level: 6 })
  const url = URL.createObjectURL(new Blob([archive as BlobPart], { type: "application/zip" }))
  const link = document.createElement("a")
  link.href = url
  link.download = `fleet_maintenance_report_${dashboard.selectedTrain}.zip`
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
